name: Lint & Test & Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
  
      - name: Install dependencies
        run: npm install

      # Check #1: Lint
      - name: Lint
        run: npm run lint

      # Check #2: Test
      - name: Test
        run: npm run test

      # Check #3: Build
      - name: Build
        run: npm run build
